insert into silver.employees(client_employee_id,first_name,middle_name,last_name,
	preferred_name,job_code,job_title,job_start_date,organization_id,organization_name,
	department_id,department_name,dob,hire_date,recent_hire_date,anniversary_date,
	term_date,years_of_experience,work_email,address,city,state,zip,country,manager_employee_id,
	manager_employee_name,fte_status,is_per_deim,cell_phone,work_phone,scheduled_weekly_hour,
	active_status,termination_reason,clinical_level,loaded_at,source_file)
select 
	client_employee_id,
	first_name,
	middle_name,
	last_name,
	preferred_name,
	job_code,
	job_title,
	job_start_date:: date,
	organization_id,
	organization_name,
	department_id,
	department_name,
	dob:: date,
	hire_date:: date,
	recent_hire_date:: date,
	anniversary_date:: date,
	nullif(term_date,''):: date,
	nullif(years_of_experience,''):: numeric(4,1),
	work_email,
	address,
	city,
	state,
	zip,
	country,
	manager_employee_id,
	manager_employee_name,
	fte_status,
	nullif(is_per_deim,''):: boolean,
	cell_phone,
	work_phone,
	nullif(scheduled_weekly_hour,''):: integer,
	nullif(active_status,''):: boolean,
	termination_reason,
	clinical_level,
	loaded_at,
	source_file
from bronze.employees