insert into silver.employees(client_employee_id,first_name,middle_name,last_name,
	preferred_name,job_code,job_title,job_start_date,organization_id,organization_name,
	department_id,department_name,dob,hire_date,recent_hire_date,anniversary_date,
	term_date,years_of_experience,work_email,address,city,state,zip,country,manager_employee_id,
	manager_employee_name,fte_status,is_per_deim,cell_phone,work_phone,scheduled_weekly_hour,
	active_status,termination_reason,clinical_level,loaded_at,source_file)
select 
	client_employee_id,
	first_name,
	middle_name,
	last_name,
	preferred_name,
	job_code,
	job_title,
	job_start_date:: date,
	organization_id,
	organization_name,
	department_id,
	TRIM(
        REGEXP_REPLACE(department_name, '^' || department_id || '\s*-\s*', '', 'i')
    ) as department_name,
	dob:: date,
	hire_date:: date,
	recent_hire_date:: date,
	(recent_hire_date::date + interval '1 year')::date as anniversary_date,
	nullif(term_date,''):: date,
	nullif(years_of_experience,''):: numeric(4,1),
	work_email,
	address,
	city,
	state,
	zip,
	country,
	manager_employee_id,
	manager_employee_name,
	fte_status,
	nullif(is_per_deim,''):: boolean,
	cell_phone,
	work_phone,
	nullif(scheduled_weekly_hour,''):: integer,
	nullif(active_status,''):: boolean,
	termination_reason,
	clinical_level,
	loaded_at,
	source_file
from bronze.employees b
where b.loaded_at>(select coalesce(max(loaded_at),'2000-01-01'::timestamp) from silver.employees)
on conflict (client_employee_id)
do update SET
	first_name = EXCLUDED.first_name,
    middle_name = EXCLUDED.middle_name,
    last_name = EXCLUDED.last_name,
    preferred_name = EXCLUDED.preferred_name,
    job_code = EXCLUDED.job_code,
    job_title = EXCLUDED.job_title,
    job_start_date = EXCLUDED.job_start_date,
    organization_id = EXCLUDED.organization_id,
    organization_name = EXCLUDED.organization_name,
    department_id = EXCLUDED.department_id,
    department_name = EXCLUDED.department_name,
    dob = EXCLUDED.dob,
    hire_date = EXCLUDED.hire_date,
    recent_hire_date = EXCLUDED.recent_hire_date,
    anniversary_date = EXCLUDED.anniversary_date,
    term_date = EXCLUDED.term_date,
    years_of_experience = EXCLUDED.years_of_experience,
    work_email = EXCLUDED.work_email,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    country = EXCLUDED.country,
    manager_employee_id = EXCLUDED.manager_employee_id,
    manager_employee_name = EXCLUDED.manager_employee_name,
    fte_status = EXCLUDED.fte_status,
    is_per_deim = EXCLUDED.is_per_deim,
    cell_phone = EXCLUDED.cell_phone,
    work_phone = EXCLUDED.work_phone,
    scheduled_weekly_hour = EXCLUDED.scheduled_weekly_hour,
    active_status = EXCLUDED.active_status,
    termination_reason = EXCLUDED.termination_reason,
    clinical_level = EXCLUDED.clinical_level,
    loaded_at = EXCLUDED.loaded_at,
    source_file = EXCLUDED.source_file;