CREATE TABLE IF NOT EXISTS silver.timesheets (
    timesheet_id BIGSERIAL PRIMARY KEY,
    client_employee_id VARCHAR(100) NOT NULL,
    department_id VARCHAR(100),
    department_name VARCHAR(255),
    home_department_id VARCHAR(100),
    home_department_name VARCHAR(255),
    pay_code TEXT[],
    punch_in_comment TEXT[],
    punch_out_comment TEXT[],
    hours_worked NUMERIC(5,2) NOT NULL,
    punch_apply_date DATE NOT NULL,
    punch_in_datetime TIMESTAMP NOT NULL,
    punch_out_datetime TIMESTAMP NOT NULL,
    scheduled_start_datetime TIMESTAMP,
    scheduled_end_datetime TIMESTAMP,
    loaded_at TIMESTAMP NOT NULL,
    source_file VARCHAR(500) NOT NULL,
    UNIQUE(client_employee_id, punch_apply_date, punch_in_datetime)
)