CREATE table if not exists gold.dim_employees (
	client_employee_id VARCHAR(100) primary key,
	fullname VARCHAR(500) not null,
	work_email VARCHAR(255),
	dob date,
	years_of_experience NUMERIC(4,1),
	job_code VARCHAR(100),
	job_title VARCHAR(255),
	organization_name VARCHAR(255),
	department_name VARCHAR(255),
	manager_employee_id VARCHAR(100),
	job_start_date date,
	hire_date date,
	recent_hire_date date,
	anniversary_date date,
	scheduled_weekly_hour SMALLINT,
	term_date date,
	tenure SMALLINT,
	is_active BOOLEAN,
	is_rehired BOOLEAN,
	is_early_attrition BOOLEAN,
	loaded_at TIMESTAMP not null,
	source_file varchar(500) not null
);