dbt_employee_pipeline:
  outputs:
    dev:
      dbname: "{{ env_var('DB_NAME') }}"
      host: "{{ env_var('DB_HOST') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      schema: silver
      threads: 4
      type: postgres
      user: "{{ env_var('DB_USER') }}"
  target: dev
